### PR TITLE
Fix testing

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by rnelson0** [comment]
Where is https://travis-ci.org/acidprime/r10k/jobs/167426144#L153-L159 coming from? beaker-rspec and serverspec are in the acceptance group which is skipped.

**Comment by ghoneycutt** [comment]
Yeah, curious why that's getting pulled in

**Comment by ghoneycutt** [comment]
Any ideas on why the acceptance group is not being ignored as it should?

**Comment by rnelson0** [comment]
@ghoneycutt Take a look at #292, I think if you add that to your upudated `.travis.yml`, it will work okay here.

**Comment by ghoneycutt** [comment]
Someone with access should cancel these builds as they will not complete.

**Comment by rnelson0** [comment]
Wow, what the heck happened? I restarted one task and it worked, so I'm restarting the entire build. I think 1.8.7 is still gonna fail, but keeping in mind that we know it will likely fail, I'll still be happy if the system works as we expect it to.

**Comment by rnelson0** [comment]
Yep, it just dies on 1.8.7. I think we will be forced to take that out of the matrix in order to have passing tests.

**Comment by ghoneycutt** [comment]
@rnelson0 I'm good with that. We should make it official and mark the CHANGELOG saying that 1.8.7 support has been dropped, since we are no longer testing with it.

**Comment by rnelson0** [comment]
@ghoneycutt If you want to update the matrix when you get a chance, that would be awesome, but no rush - I think we'll hold off on the merge until the migration to VP is complete. That way we can ensure the `latest` version of `zack/r10k` is a 100% working version and not introduce the chance of problems for anyone not pinning or whose automation grabs the latest.

**Comment by ghoneycutt** [comment]
People who do that want to see the failures or they wouldn't consume it like that :)

**Comment by rnelson0** [comment]
There are a number of tools that grab the latest version off the forge to
automatically update Puppetfiles, and even though 999.999.999 should stand
out as "expired", it would be nice if it was still a working version (this
came up with an accidentally published 999.999.999 version in the wrong
namespace that still managed to collect a non-trivial number of downloads!).

**Comment by ghoneycutt** [comment]
It will work. Though now we are saying that we no longer support ruby 1.8.7 and puppet v2. So if you have those versions, it might work, but that's on you.

**Comment by ghoneycutt** [comment]
Whew! got it. Can I get a merge please?

**Comment by ghoneycutt** [comment]
Anything else left to get this merged?

**Comment by ghoneycutt** [comment]
Thank you!

**Pull request merged**
